### ISSUE TITLE
absolute negative values (“c:100,=-200”) aren't accepted

### ISSUE THREAD

**Issue by dan-smith** [BlueM/cliclick#39] opened 2016-09-12 16:35 UTC
The help says to prefix with = to specify absolute positions on displays left of (/above) the main display:
```
(If you need to specify absolute negative values in case you have a setup 
with a second display arranged to the left of your main display, prefix the 
number with “=”, for instance “c:100,=-200”.)
```
However this isn't working for me:
```
$ ./cliclick p
Current mouse position: -1039,-1328
$ ./cliclick c:=-1039,=-1328
Invalid X axis coordinate “=-1039” given
```

If I try that without the = I get a click at a relative position (as expected).

Perhaps I misunderstood the format?

**Comment by BlueM** [comment] 2016-09-12 16:38
This is a duplicate of #32, which was fixed with 95f3a73d5231f455fb787883921b0aa529531fae. Note: this change is not in the cliclick distribution, so the problem can be observed with the latest version, but it should work as advertised with a version built from `dev/master`

**Closed by BlueM** 2016-09-12 16:38 UTC
Labels: duplicate
